spring:
  rabbitmq:
    addresses: 192.168.3.107:5672
    username: admin
    password: 123456
    virtual-host: /
    publisher-confirms: true #confirm模式
    publisher-returns: true #return机制
    template:
      mandatory: true #与return机制结合配置次属性
    connection-timeout: 5000
server:
  port: 8081
  servlet:
    context-path: /

pb:
  test:
    pre:a
    suf:b